### ISSUE TITLE
Byte ordering wrong?

### ISSUE THREAD

**Issue by cbsmith** [otoolep/cppuuid#1]
I could be mistaken, but I _believe_ your code will only have the byte ordering of the raw 128-bits correct on a big endian platform.

**Comment by otoolep** [comment]
Can you point at a specific line of code that this might be true about?

**Comment by cbsmith** [comment]
For example, you record the time as:

upper_ = (uint64_t) time_low << 32;

Which means the byte order of those 4 bytes will be dependent on the byte ordering of uint64_t (which will be different depending on the endianess of the platform), but the RFC states those 32-bits must be in big endian order. I think you need to do something like:

upper_ = ((uint64_t) htonl(time_low)) << 32;

Better still is probably to represent the uuid as a sequence of bytes and use Rob Pike's approach to ensuring endian correctness: http://commandcenter.blogspot.com/2012/04/byte-order-fallacy.html

**Comment by otoolep** [comment]
@cbsmith -- thanks, it seems you're right. I actually found some other production-level code I had written elsewhere that used a copy-n-pasted copy of some of this code, and it _is_ making htonX calls -- I must have noticed it myself.

Yeah, the code in this repo needs some tweaking.

**Comment by otoolep** [comment]
Should be fixed now, 2 years later.
