### ISSUE TITLE
timestamp UUID

### ISSUE THREAD

**Issue by chengm349** [otoolep/cppuuid#2]
I have a UUID requirement as:

- Each session will also be represented with a Universally Unique ID (UUID), which should be a current timestamp
-  a unique UUID value set by the customer as a 64-bit value. CME Group recommends using the system timestamp which represents the number of microseconds since epoch (Jan 1, 1970) as the timestamp.
- I also need to save it in a Linux file and rebuild the UUID from the saved value.

Wondering whether your code can support it?  It seems UUID should not involve host ID according to CME (Exchange) recommendation.

**Comment by otoolep** [comment]
I don't maintain this repo anymore, so unfortunately can't help.
